### PR TITLE
Base branch for 2021-07 updates

### PR DESCRIPTION
**Pull request by dominiquesydow**
Let's use this branch as base branch for all 2021-07 updates.

Tick off your notebook when you have merged your updates into this base branch :)

- [x] ` week1_session1_grundkonzepte.ipynb`
- [x] `week1_session2_numpy_pandas.ipynb` | [PR](https://github.com/volkamerlab/ai_in_medicine/pull/19)
- [x] `week1_session3_matplotlib.ipynb`
- [x] `week1_session4_intro_to_ml_and_scikit_learn.ipynb`
- [x] `week1_session5_deep_learning.ipynb`
- [x] `week2_session1_cadd_exercise.ipynb`
- [x] `week2_session2_images-MRI-dl.ipynb`

### CODE REVIEW

**Comment by derEitel** [comment]
Hi, just uploaded my script (it's renamed to follow the underscore convention fully). To download the data I have links that currently point to this branch, will this branch be deleted before the course? If not all is great, if yes, I need to change those links to point to master.

**Comment by dominiquesydow** [comment]
@derEitel, thanks! This branch will be merged into `master`, so please do rename your links.

**Comment by dominiquesydow** [comment]
Does anyone use these datasets? @git-mojo, we are the only two using COVID19 data, right?
image

**Comment by git-mojo** [comment]
> Does anyone use these datasets? @git-mojo, we are the only two using COVID19 data, right?
> image
> 
> I do not need them, so from my side they can go.

**Pull request merged**
