### PR TITLE
first version of week2 session2 and data

### PR DESCRIPTION
**Pull request by derEitel**
Open questions:

- [x] General structure
- [ ] Difficulty
- [ ] Length

### CODE REVIEW

**Comment by jaimergp** [comment]
This. is. so. cool.

**Comment by derEitel** [comment]
> This. is. so. cool.

You mean the car, I guess?

**Comment by jaimergp** [comment]
Yes, but also the full notebook. Working on images like that is super visual and rewarding for new learners!

**Comment by derEitel** [comment]
Cool, glad you like it :)
I tested in on Azure and included the required installations. This should be the final form now (unless week 1 calls for major changes) and is ready for merging.

**Comment by jaimergp** [comment]
I'll merge over the weekend and create the Azure project for the students to clone in week 2!

**Comment by derEitel** [comment]
Thanks Jaime!

**Pull request merged**
