### PR TITLE
CADD Exercise

### PR DESCRIPTION
**Pull request by schallerdavid**
This PR adds a CADD exercise for the second week. The solutions are only for the review and will be removed before the exercise starts.

## To Do
- [x] add EGFR activity data
- [x] add notebook exercise with solutions
- [x] runs on Azure

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by AndreaVolkamer** [comment]
@schallerdavid great notebook, I really like the guidance through the topic!
I leave a more detailed review to Moritz, just two suggestions of things that could be changed:
* how about we omit the IC50 to pIC50 conversion? It adds not much to the classification task, and one could get easily confused by having to deal with the log calculation?
* and could you add a very short intro to what SMILES are?

**Comment by git-mojo** [comment]
Nice notebook :) Just some points:
- Why do you use the neglog here?
- Intro to SMILES and SMARTS
- I just introduced the object-oriented API in matplotlib and not pyplot API. I can send you the code for the ROC curve using the object-oriented API for consistency or you have to shortly guide them through the code, but they should be able to understand it.
- Are you going to guide them through the whole notebook or are these partly solutions to some exercises?

**Comment by dominiquesydow** [comment]
> Not sure if Dominique(@dominiquesydow) has introduced .loc()...

Yes, will introduce this tomorrow morning :)

> I just introduced the object-oriented API in matplotlib and not pyplot API. I can send you the code for the ROC curve using the object-oriented API for consistency or you have to shortly guide them through the code, but they should be able to understand it.

Sticking to packages they already know sounds preferable to me.

**Comment by schallerdavid** [comment]
@AndreaVolkamer, @git-mojo and @dominiquesydow thanks for your feedback. I will implement your seggestions.

>     * I just introduced the object-oriented API in matplotlib and not pyplot API. I can send you the code for the ROC curve using the object-oriented API for consistency or you have to shortly guide them through the code, but they should be able to understand it.
The solution I prepared is based on the [ml and sklearn intro of session 4](https://github.com/volkamerlab/ai_in_medicine/blob/update-2020.07/week1_session4_intro_to_ml_and_scikit_learn.ipynb). This notebook also uses the support vector classifier and plots the ROC curve with pyplot, so I thought I might stick to that version.

**Comment by AndreaVolkamer** [comment]
to be consistent, maybe @iamzoltan you want to adapt your's also? but not sure that will create some issues, because the students need to push/clone the stuff again? @jaimergp how will we include the additional notebooks anyways?

**Comment by jaimergp** [comment]
We agreed on cloning a second repo for week two, so I'd rather not update this week's...

**Comment by schallerdavid** [comment]
## Progress
- [x] added SMILES introduction with small exercise
- [x] converted pIC50 to IC50

## PyPlot
Since my solution will be deleted anyway, it's a little bit up to them what they use. However, it would be great if @git-mojo can send me the proper object-oriented version, so I have it in hand in case anyone asks.

If everyone is fine with the current version, I would keep it as it is and remove the solutions tomorrow. Then we are ready to merge.

Thanks for your help!

**Comment by jaimergp** [comment]
You can (should?) leave the solutions in! I'll clean everything before porting to Azure.

**Comment by schallerdavid** [comment]
Alrighty, then we are ready to go!

**Pull request merged**
