### PR TITLE
Update 2020.07 ms

### PR DESCRIPTION
**Pull request by git-mojo**

### CODE REVIEW

**Comment by dominiquesydow** [comment]
@git-mojo, I love this!!!

**Comment by dominiquesydow** [comment]
@iamzoltan, I see that @git-mojo focuses on `matplotlib` and that you used `seaborn`. In order to go over a package again that the students already are familiar with, maybe you want to switch to matplotlib as well?

**Comment by dominiquesydow** [comment]
@git-mojo, since you removed `seaborn`, do you want to drop it also from the notebook's name? Or do you talk about it in your slides?

**Comment by jaimergp** [comment]
For the future, I think it'll be less confusing to reply in a new comment instead of editing inline 🤣 For a second I thought Dominique was a having a super cool monologue!

**Comment by dominiquesydow** [comment]
True, reading it is hilarious though!!! :)

**Comment by git-mojo** [comment]
Done :)

**Pull request merged**
